services:
  interface:
    container_name: interface
    image: ghcr.io/maexled/mystrom-django-interface:master
#   build: .
    privileged: true
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env

  requester:
    container_name: interface-requester
    image: curlimages/curl:7.80.0
    command: ["sh", "-c", "while true; do sleep 60; curl -X POST http://interface:8000/shelly-api/devices/request-and-save-results >/dev/null 2>&1 & curl -X POST http://interface:8000/api/devices/request-and-save-results >/dev/null 2>&1; done"]    
    depends_on:
      - interface

