version: "3.7"

services:
  interface:
    container_name: interface
    image: ghcr.io/maexled/mystrom-django-interface:master
#   build: .
    privileged: true
    restart: always
    ports:
      - "80:8000"
    environment:
      - ENGINE_TYPE=${ENGINE_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS},interface
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
      - CHART_TYPE=${CHART_TYPE}
      - TZ=${TZ}

  requester:
    container_name: interface-requester
    image: curlimages/curl:7.80.0
    command: ["sh", "-c", "while true; do sleep 60; curl -X POST http://interface:8000/shelly-api/devices/request-and-save-results >/dev/null 2>&1 & curl -X POST http://interface:8000/api/devices/request-and-save-results >/dev/null 2>&1; done"]    
    depends_on:
      - interface

