# Generated by Django 4.0.5 on 2022-06-08 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystrom_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystromdevice',
            name='ip',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Not valid IP Address', regex='^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])|localhost$')]),
        ),
    ]
