# Generated by Django 4.0.5 on 2022-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystrom_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystromdevice",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
