# Generated by Django 5.0.7 on 2024-07-20 14:32

from django.db import migrations


def forwards(apps, schema_editor):
    # Create a new temporary table with the desired schema
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE results_temp (
                date TIMESTAMPTZ NOT NULL,
                device_id INTEGER NOT NULL,
                power FLOAT,
                ws FLOAT,
                relay INTEGER,
                temperature FLOAT,
                PRIMARY KEY (date, device_id)
            )
        """)

        # Copy data from the old table to the new table
        cursor.execute("""
            INSERT INTO results_temp (date, device_id, power, ws, relay, temperature)
            SELECT date, device_id, power, ws, relay, temperature
            FROM results
        """)

        # Drop the old table
        cursor.execute("""
            DROP TABLE results
        """)

        # Rename the new table to the original table name
        cursor.execute("""
            ALTER TABLE results_temp
            RENAME TO results
        """)

        # Create hypertable
        cursor.execute("""
            SELECT create_hypertable('results', 'date', migrate_data => true)
        """)

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mystrom_rest', '0002_mystromdevice_active'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
