# Generated by Django 5.0.7 on 2024-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mystrom_rest", "0003_auto_20240720_1432"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mystromresult",
            options={"managed": False},
        ),
    ]
