# Generated by Django 4.0.5 on 2022-10-22 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxCubeDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Not valid IP Address', regex='^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$')])),
            ],
            options={
                'db_table': 'maxcubes',
            },
        ),
        migrations.CreateModel(
            name='MaxCubeThermostatResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('room_id', models.IntegerField()),
                ('serial', models.CharField(max_length=16)),
                ('actual_temperature', models.FloatField()),
                ('target_temperature', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maxcube_rest.maxcubedevice')),
            ],
            options={
                'db_table': 'maxcube_thermostat_results',
            },
        ),
    ]
