# Generated by Django 4.0.5 on 2022-06-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystrom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MystromDevice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='MystromResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('power', models.FloatField()),
                ('ws', models.FloatField()),
                ('relay', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mystrom.mystromdevice')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
