# Generated by Django 4.0.5 on 2022-06-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystrom', '0002_mystromdevice_mystromresult_delete_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystromresult',
            name='device_id',
        ),
        migrations.DeleteModel(
            name='MystromDevice',
        ),
        migrations.DeleteModel(
            name='MystromResult',
        ),
    ]
